export default {
  lang: "en",
  language: "Language",
  spanish: "Spanish",
  english: "English",
  start: "Start",
  logout: "Log out",
  timer: "Timer",
  rounds: "Rounds",
  round: "Round",
  seconds: "Seconds",
  word_category: "Category",
  videogames: "Video game",
  draw_this_word: "Draw this word",
  choose_a_word: "Choose a word",
  guessed_it: "Guessed it!",
  continue: "Continue",
  no_one_guessed: "No one guessed",
  try_again: "Try again!",
  game_over: "Game over!",
  scores_from_this_match: "Scores from this match",
  restart: "Restart",
  hide_this_box: "Hide this box",
  or: "or",
  place_your_camera_here: "Place your camera here",
  before_you_start_the_game: "Before you start the game",
  waiting_for_the_streamer_to_start_the_game: "Waiting for the streamer to start the game..."
};