export default {
  lang: "en",
  language: "Language",
  spanish: "Spanish",
  english: "English",
  start: "Start",
  logout: "Log out",
  timer: "Timer",
  rounds: "Rounds",
  round: "Round",
  seconds: "Seconds",
  word_category: "Category",
  videogames: "Video game",
  draw_this_word: "Draw this word",
  choose_a_word: "Choose a word",
  guessed_it: "Guessed it!",
  continue: "Continue",
  no_one_guessed: "No one guessed",
  try_again: "Try again!",
};