export default {
  lang: "es",
  language: "Idioma",
  spanish: "Español",
  english: "Inglés",
  start: "Empezar",
  logout: "Salir",
  timer: "Temporizador",
  rounds: "Rondas",
  round: "Ronda",
  seconds: "Segundos",
  word_category: "Categoría",
  videogames: "Videojuego",
  draw_this_word: "Dibuja esta palabra",
  choose_a_word: "Elige una palabra",
  guessed_it: "¡Ha adivinado!",
  continue: "Continuar",
  no_one_guessed: "Nadie ha adivinado",
  try_again: "¡Vuelve a intentarlo!",
  end_of_the_game: "Fin del juego",
  restart: "Reiniciar",
};