export default {
  lang: "es",
  language: "Idioma",
  spanish: "Español",
  english: "Inglés",
  start: "Empezar",
  logout: "Cerrar sesión",
  timer: "Temporizador",
  rounds: "Rondas",
  round: "Ronda",
  seconds: "Segundos",
  word_category: "Categoría",
  videogame: "Videojuego",
  videogames: "Videojuegos",
  custom: "Personalizado",
  draw_this_word: "Dibuja esta palabra",
  write_a_word: "Escribe una palabra",
  choose_a_word: "Elige una palabra",
  word: "Palabra",
  guessed_it: "¡Ha adivinado!",
  continue: "Continuar",
  no_one_guessed: "Nadie adivinó",
  try_again: "¡Vuelve a intentarlo!",
  game_over: "¡Juego terminado!",
  scores_from_this_match: "Puntuaciones de esta partida",
  restart: "Reiniciar",
  hide_this_box: "Oculte esta caja",
  or: "o",
  place_your_camera_here: "Coloque su cámara aquí",
  before_you_start_the_game: "Antes de empezar el juego",
  waiting_for_the_streamer_to_start_the_game: "Esperando a que el streamer inicie el juego...",
  challenge_and_play_with_your_audience_to_guess_your_drawings: "Desafía y juega con tu audiencia a adivinar tus dibujos.",
};