export default {
  lang: "es",
  language: "Idioma",
  spanish: "Español",
  english: "Inglés",
  start: "Empezar",
  logout: "Salir",
  timer: "Temporizador",
  rounds: "Rondas",
  round: "Ronda",
  seconds: "Segundos",
  word_category: "Categoría",
  videogames: "Videojuego",
  draw_this_word: "Dibuja esta palabra",
  choose_a_word: "Elige una palabra",
  guessed_it: "¡Ha adivinado!",
  continue: "Continuar",
  no_one_guessed: "Nadie adivinó",
  try_again: "¡Vuelve a intentarlo!",
  game_over: "¡Juego terminado!",
  scores_from_this_match: "Puntuaciones de esta partida",
  restart: "Reiniciar",
  hide_this_box: "Oculte esta caja",
  or: "o",
  place_your_camera_here: "Coloque su cámara aquí",
  before_you_start_the_game: "Antes de empezar el juego",
};