export default {
  objects: {
    id: "objects",
    title: "Objects",
    words: {
      ball: "Ball",
      pencil: "Pencil",
      chair: "Chair",
      watch: "Watch",
      balloon: "Balloon",
      book: "Book",
      box: "Box",
      cup: "Cup",
      phone: "Phone",
      car: "Car",
      bicycle: "Bicycle",
      hammer: "Hammer",
      computer: "Computer",
      lamp: "Lamp",
      pants: "Pants",
      shirt: "Shirt",
      shoes: "Shoes",
      glasses: "Glasses",
      hat: "Hat",
      perfume: "Perfume",
      camera: "Camera",
      toothbrush: "Toothbrush",
      mirror: "Mirror",
      lock: "Lock",
      key: "Key",
      bag: "Bag",
      suitcase: "Suitcase",
      umbrella: "Umbrella",
      music_box: "Music Box",
      wallet: "Wallet",
      piano: "Piano",
      guitar: "Guitar",
      violin: "Violin",
      stuffed_animal: "Stuffed Animal",
      bed: "Bed",
      table: "Table",
      kitchen: "Kitchen",
      fridge: "Fridge",
      hairbrush: "Hairbrush",
      comb: "Comb",
      bottle: "Bottle",
      newspaper: "Newspaper",
      magazine: "Magazine",
      tools: "Tools",
      broom: "Broom",
      plant: "Plant",
      painting: "Painting",
      ladder: "Ladder",
      paper: "Paper",
      canvas: "Canvas",
      needle_and_thread: "Needle and Thread",
      pen: "Pen",
      feather: "Feather",
      eraser: "Eraser",
      tape: "Tape",
      ruler: "Ruler",
      palette: "Palette",
      radio: "Radio",
      speakers: "Speakers",
      keyboard: "Keyboard",
      mouse: "Mouse",
      calculator: "Calculator",
      scissors: "Scissors",
      pillow: "Pillow",
      blanket: "Blanket",
      alarm_clock: "Alarm Clock",
      toy: "Toy",
      crayons: "Crayons",
      markers: "Markers",
      tape_measure: "Tape Measure",
      sunglasses: "Sunglasses",
      tie: "Tie",
      keychain: "Keychain",
      calendar: "Calendar",
      stamp: "Stamp",
      ashtray: "Ashtray",
      teapot: "Teapot",
      glass: "Glass",
      plate: "Plate",
      spoon: "Spoon",
      fork: "Fork",
      knife: "Knife",
      can_opener: "Can Opener",
      candleholder: "Candleholder",
      microphone: "Microphone",
      toaster: "Toaster",
      microwave: "Microwave",
      oven: "Oven",
      refrigerator: "Refrigerator",
      shower: "Shower",
      washing_machine: "Washing machine",
      coffee: "Coffee",
      coffee_maker: "Coffee maker",
      tablet: "Tablet",
      television: "Television",
      printer: "Printer",
      headphones: "Headphones",
      door: "Door",
      window: "Window",
      fan: "Fan",
    }
  },
  countries: {
    id: "countries",
    title: "Countries",
    words: {
      afghanistan: "Afghanistan",
      albania: "Albania",
      algeria: "Algeria",
      andorra: "Andorra",
      angola: "Angola",
      anguilla: "Anguilla",
      antarctica: "Antarctica",
      antigua_and_barbuda: "Antigua and Barbuda",
      argentina: "Argentina",
      armenia: "Armenia",
      aruba: "Aruba",
      australia: "Australia",
      austria: "Austria",
      azerbaijan: "Azerbaijan",
      bahamas: "Bahamas",
      bahrain: "Bahrain",
      bangladesh: "Bangladesh",
      barbados: "Barbados",
      belarus: "Belarus",
      belgium: "Belgium",
      belize: "Belize",
      benin: "Benin",
      bermuda: "Bermuda",
      bhutan: "Bhutan",
      bolivia: "Bolivia",
      bosnia_and_herzegovina: "Bosnia and Herzegovina",
      botswana: "Botswana",
      brazil: "Brazil",
      brunei_darussalam: "Brunei Darussalam",
      bulgaria: "Bulgaria",
      burkina_faso: "Burkina Faso",
      burundi: "Burundi",
      cambodia: "Cambodia",
      cameroon: "Cameroon",
      canada: "Canada",
      central_african_republic: "Central African Republic",
      chad: "Chad",
      chile: "Chile",
      china: "China",
      colombia: "Colombia",
      comoros: "Comoros",
      congo: "Congo",
      costa_rica: "Costa Rica",
      croatia: "Croatia",
      cuba: "Cuba",
      curacao: "Curaçao",
      cyprus: "Cyprus",
      czechia: "Czechia",
      cote_divoire: "Côte d'Ivoire",
      denmark: "Denmark",
      djibouti: "Djibouti",
      dominica: "Dominica",
      dominican_republic: "Dominican Republic",
      ecuador: "Ecuador",
      egypt: "Egypt",
      el_salvador: "El Salvador",
      equatorial_guinea: "Equatorial Guinea",
      eritrea: "Eritrea",
      estonia: "Estonia",
      eswatini: "Eswatini",
      ethiopia: "Ethiopia",
      falkland_islands_malvinas: "Falkland Islands",
      fiji: "Fiji",
      finland: "Finland",
      france: "France",
      french_guiana: "French Guiana",
      gabon: "Gabon",
      gambia: "Gambia",
      georgia: "Georgia",
      germany: "Germany",
      ghana: "Ghana",
      gibraltar: "Gibraltar",
      greece: "Greece",
      greenland: "Greenland",
      grenada: "Grenada",
      guadeloupe: "Guadeloupe",
      guam: "Guam",
      guatemala: "Guatemala",
      guernsey: "Guernsey",
      guinea: "Guinea",
      guinea_bissau: "Guinea-Bissau",
      guyana: "Guyana",
      haiti: "Haiti",
      honduras: "Honduras",
      hong_kong: "Hong Kong",
      hungary: "Hungary",
      iceland: "Iceland",
      india: "India",
      indonesia: "Indonesia",
      iran: "Iran",
      iraq: "Iraq",
      ireland: "Ireland",
      israel: "Israel",
      italy: "Italy",
      jamaica: "Jamaica",
      japan: "Japan",
      jersey: "Jersey",
      jordan: "Jordan",
      kazakhstan: "Kazakhstan",
      kenya: "Kenya",
      kiribati: "Kiribati",
      kosovo: "Kosovo",
      kuwait: "Kuwait",
      kyrgyzstan: "Kyrgyzstan",
      laos: "Laos",
      latvia: "Latvia",
      lebanon: "Lebanon",
      lesotho: "Lesotho",
      liberia: "Liberia",
      libya: "Libya",
      liechtenstein: "Liechtenstein",
      lithuania: "Lithuania",
      luxembourg: "Luxembourg",
      macao: "Macao",
      madagascar: "Madagascar",
      malawi: "Malawi",
      malaysia: "Malaysia",
      maldives: "Maldives",
      mali: "Mali",
      malta: "Malta",
      martinique: "Martinique",
      mauritania: "Mauritania",
      mauritius: "Mauritius",
      mayotte: "Mayotte",
      mexico: "Mexico",
      micronesia: "Micronesia",
      moldova: "Moldova",
      monaco: "Monaco",
      mongolia: "Mongolia",
      montenegro: "Montenegro",
      montserrat: "Montserrat",
      morocco: "Morocco",
      mozambique: "Mozambique",
      myanmar: "Myanmar",
      namibia: "Namibia",
      nauru: "Nauru",
      nepal: "Nepal",
      netherlands: "Netherlands",
      new_caledonia: "New Caledonia",
      new_zealand: "New Zealand",
      nicaragua: "Nicaragua",
      niger: "Niger",
      nigeria: "Nigeria",
      niue: "Niue",
      north_korea: "North Korea",
      north_macedonia: "North Macedonia",
      norway: "Norway",
      oman: "Oman",
      pakistan: "Pakistan",
      palau: "Palau",
      palestine: "Palestine",
      panama: "Panama",
      papua_new_guinea: "Papua New Guinea",
      paraguay: "Paraguay",
      peru: "Peru",
      philippines: "Philippines",
      poland: "Poland",
      portugal: "Portugal",
      puerto_rico: "Puerto Rico",
      qatar: "Qatar",
      romania: "Romania",
      russia: "Russia",
      rwanda: "Rwanda",
      reunion: "Réunion",
      samoa: "Samoa",
      san_marino: "San Marino",
      saudi_arabia: "Saudi Arabia",
      senegal: "Senegal",
      serbia: "Serbia",
      seychelles: "Seychelles",
      sierra_leone: "Sierra Leone",
      singapore: "Singapore",
      slovakia: "Slovakia",
      slovenia: "Slovenia",
      somalia: "Somalia",
      south_africa: "South Africa",
      south_korea: "South Korea",
      south_sudan: "South Sudan",
      spain: "Spain",
      sri_lanka: "Sri Lanka",
      sudan: "Sudan",
      suriname: "Suriname",
      sweden: "Sweden",
      switzerland: "Switzerland",
      syria: "Syria",
      taiwan: "Taiwan",
      tajikistan: "Tajikistan",
      tanzania: "Tanzania",
      thailand: "Thailand",
      timor_leste: "Timor-Leste",
      togo: "Togo",
      tonga: "Tonga",
      trinidad_and_tobago: "Trinidad and Tobago",
      tunisia: "Tunisia",
      turkmenistan: "Turkmenistan",
      tuvalu: "Tuvalu",
      turkiye: "Türkiye",
      uganda: "Uganda",
      ukraine: "Ukraine",
      united_arab_emirates: "United Arab Emirates",
      united_kingdom: "United Kingdom",
      united_states: "United States",
      uruguay: "Uruguay",
      uzbekistan: "Uzbekistan",
      vanuatu: "Vanuatu",
      vatican_city_state: "Vatican City",
      venezuela: "Venezuela",
      vietnam: "Vietnam",
      western_sahara: "Western Sahara",
      yemen: "Yemen",
      zambia: "Zambia",
      zimbabwe: "Zimbabwe"
    }
  },
  games: {
    id: "games",
    title: "Video games",
    game_type: {
      lol: {
        id: "lol",
        game_name: "League of Legends",
        words: {
          aatrox: "Aatrox",
          ahri: "Ahri",
          akali: "Akali",
          akshan: "Akshan",
          alistar: "Alistar",
          amumu: "Amumu",
          anivia: "Anivia",
          annie: "Annie",
          aphelios: "Aphelios",
          ashe: "Ashe",
          aurelion_sol: "Aurelion Sol",
          azir: "Azir",
          bard: "Bard",
          bel_veth: "Bel'veth",
          blitzcrank: "Blitzcrank",
          brand: "Brand",
          braum: "Braum",
          caitlyn: "Caitlyn",
          camille: "Camille",
          cassiopeia: "Cassiopeia",
          cho_gath: "Cho'Gath",
          corki: "Corki",
          darius: "Darius",
          diana: "Diana",
          dr_mundo: "Dr Mundo",
          draven: "Draven",
          ekko: "Ekko",
          evelynn: "Evelynn",
          ezreal: "Ezreal",
          fiddlesticks: "Fiddlesticks",
          fiora: "Fiora",
          gangplank: "Gangplank",
          garen: "Garen",
          gnar: "Gnar",
          gragas: "Gragas",
          graves: "Graves",
          gwen: "Gwen",
          hecarim: "Hecarim",
          heimerdinger: "Heimerdinger",
          illaoi: "Illaoi",
          irelia: "Irelia",
          ivern: "Ivern",
          janna: "Janna",
          jarvan_iv: "Jarvan IV",
          jax: "Jax",
          jayce: "Jayce",
          jhin: "Jhin",
          jinx: "Jinx",
          k_sante: "K'Sante",
          kai_sa: "Kai'Sa",
          kalista: "Kalista",
          karma: "Karma",
          karthus: "Karthus",
          kassadin: "Kassadin",
          katarina: "Katarina",
          kayle: "Kayle",
          kayn: "Kayn",
          kennen: "Kennen",
          kha_zix: "Kha'Zix",
          kindred: "Kindred",
          kled: "Kled",
          kog_maw: "Kog'Maw",
          leblanc: "LeBlanc",
          lee_sin: "Lee Sin",
          leona: "Leona",
          lillia: "Lillia",
          lissandra: "Lissandra",
          lucian: "Lucian",
          lulu: "Lulu",
          lux: "Lux",
          malphite: "Malphite",
          malzahar: "Malzahar",
          maokai: "Maokai",
          master_yi: "Master Yi",
          milio: "Milio",
          miss_fortune: "Miss Fortune",
          mordekaiser: "Mordekaiser",
          morgana: "Morgana",
          naafiri: "Naafiri",
          nami: "Nami",
          nasus: "Nasus",
          nautilus: "Nautilus",
          neeko: "Neeko",
          nidalee: "Nidalee",
          nilah: "Nilah",
          nocturne: "Nocturne",
          nunu: "Nunu",
          olaf: "Olaf",
          orianna: "Orianna",
          ornn: "Ornn",
          pantheon: "Pantheon",
          poppy: "Poppy",
          pyke: "Pyke",
          qiyana: "Qiyana",
          quinn: "Quinn",
          rakan: "Rakan",
          rammus: "Rammus",
          rek_sai: "Rek'Sai",
          rell: "Rell",
          renata_glasc: "Renata Glasc",
          renekton: "Renekton",
          rengar: "Rengar",
          riven: "Riven",
          rumble: "Rumble",
          ryze: "Ryze",
          samira: "Samira",
          sejuani: "Sejuani",
          senna: "Senna",
          seraphine: "Seraphine",
          sett: "Sett",
          shaco: "Shaco",
          shen: "Shen",
          shyvana: "Shyvana",
          singed: "Singed",
          sion: "Sion",
          sivir: "Sivir",
          skarner: "Skarner",
          sona: "Sona",
          soraka: "Soraka",
          swain: "Swain",
          sylas: "Sylas",
          syndra: "Syndra",
          tahm_kench: "Tahm Kench",
          taliyah: "Taliyah",
          talon: "Talon",
          taric: "Taric",
          teemo: "Teemo",
          thresh: "Thresh",
          tristana: "Tristana",
          trundle: "Trundle",
          tryndamere: "Tryndamere",
          twitch: "Twitch",
          udyr: "Udyr",
          urgot: "Urgot",
          varus: "Varus",
          vayne: "Vayne",
          veigar: "Veigar",
          velkoz: "Vel'Koz",
          vex: "Vex",
          vi: "Vi",
          viego: "Viego",
          viktor: "Viktor",
          vladimir: "Vladimir",
          volibear: "Volibear",
          warwick: "Warwick",
          wukong: "Wukong",
          xayah: "Xayah",
          xerath: "Xerath",
          xin_zhao: "Xin Zhao",
          yasuo: "Yasuo",
          yone: "Yone",
          yorick: "Yorick",
          yuumi: "Yuumi",
          zac: "Zac",
          zed: "Zed",
          zeri: "Zeri",
          ziggs: "Ziggs",
          zilean: "Zilean",
          zoe: "Zoe",
          zyra: "Zyra"
        }
      },
      valorant: {
        id: "valorant",
        game_name: "Valorant",
        words: {
          astra: "Astra",
          breach: "Breach",
          brimstone: "Brimstone",
          chamber: "Chamber",
          cypher: "Cypher",
          deadlock: "Deadlock",
          fade: "Fade",
          gekko: "Gekko",
          harbor: "Harbor",
          jett: "Jett",
          kayo: "Kayo",
          killjoy: "Killjoy",
          neon: "Neon",
          omen: "Omen",
          phoenix: "Phoenix",
          raze: "Raze",
          reyna: "Reyna",
          sage: "Sage",
          skye: "Skye",
          sova: "Sova",
          viper: "Viper",
          yoru: "Yoru",
          classic: "Classic",
          ghost: "Ghost",
          shorty: "Shorty",
          frenzy: "Frenzy",
          sheriff: "Sheriff",
          stinger: "Stinger",
          spectre: "Spectre",
          bucky: "Bucky",
          judge: "Judge",
          bulldog: "Bulldog",
          guardian: "Guardian",
          phantom: "Phantom",
          vandal: "Vandal",
          marshal: "Marshal",
          operator: "Operator",
          ares: "Ares",
          odin: "Odin",
          knife: "Knife",
        }
      }
    }
  }
};