export default {
  objects: {
    id: "objects",
    title: "Objects",
    words: {
      ball: "Ball",
      pencil: "Pencil",
      chair: "Chair",
      watch: "Watch",
      balloon: "Balloon",
      book: "Book",
      box: "Box",
      cup: "Cup",
      phone: "Phone",
      car: "Car",
      bicycle: "Bicycle",
      hammer: "Hammer",
      computer: "Computer",
      lamp: "Lamp",
      brush: "Brush",
      pants: "Pants",
      shirt: "Shirt",
      shoes: "Shoes",
      glasses: "Glasses",
      hat: "Hat",
      perfume: "Perfume",
      camera: "Camera",
      toothbrush: "Toothbrush",
      mirror: "Mirror",
      lock: "Lock",
      key: "Key",
      bag: "Bag",
      suitcase: "Suitcase",
      umbrella: "Umbrella",
      music_box: "Music Box",
      wallet: "Wallet",
      purse: "Purse",
      piano: "Piano",
      guitar: "Guitar",
      violin: "Violin",
      stuffed_animal: "Stuffed Animal",
      bed: "Bed",
      table: "Table",
      kitchen: "Kitchen",
      fridge: "Fridge",
      hairbrush: "Hairbrush",
      comb: "Comb",
      bottle: "Bottle",
      newspaper: "Newspaper",
      magazine: "Magazine",
      tools: "Tools",
      broom: "Broom",
      plant: "Plant",
      painting: "Painting",
      ladder: "Ladder",
      paper: "Paper",
      canvas: "Canvas",
      needle_and_thread: "Needle and Thread",
      pen: "Pen",
      feather: "Feather",
      eraser: "Eraser",
      tape: "Tape",
      ruler: "Ruler",
      palette: "Palette",
      radio: "Radio",
      speakers: "Speakers",
      keyboard: "Keyboard",
      mouse: "Mouse",
      calculator: "Calculator",
      scissors: "Scissors",
      pillow: "Pillow",
      blanket: "Blanket",
      alarm_clock: "Alarm Clock",
      toy: "Toy",
      crayons: "Crayons",
      markers: "Markers",
      tape_measure: "Tape Measure",
      sunglasses: "Sunglasses",
      tie: "Tie",
      keychain: "Keychain",
      calendar: "Calendar",
      stamp: "Stamp",
      ashtray: "Ashtray",
      teapot: "Teapot",
      glass: "Glass",
      plate: "Plate",
      spoon: "Spoon",
      fork: "Fork",
      knife: "Knife",
      can_opener: "Can Opener",
      candleholder: "Candleholder"
    }
  },
  countries: {
    id: "countries",
    title: "Countries",
    words: {
      afghanistan: "Afghanistan",
      albania: "Albania",
      algeria: "Algeria",
      andorra: "Andorra",
      angola: "Angola",
      anguilla: "Anguilla",
      antarctica: "Antarctica",
      antigua_and_barbuda: "Antigua and Barbuda",
      argentina: "Argentina",
      armenia: "Armenia",
      aruba: "Aruba",
      australia: "Australia",
      austria: "Austria",
      azerbaijan: "Azerbaijan",
      bahamas: "Bahamas",
      bahrain: "Bahrain",
      bangladesh: "Bangladesh",
      barbados: "Barbados",
      belarus: "Belarus",
      belgium: "Belgium",
      belize: "Belize",
      benin: "Benin",
      bermuda: "Bermuda",
      bhutan: "Bhutan",
      bolivia: "Bolivia",
      bosnia_and_herzegovina: "Bosnia and Herzegovina",
      botswana: "Botswana",
      brazil: "Brazil",
      brunei_darussalam: "Brunei Darussalam",
      bulgaria: "Bulgaria",
      burkina_faso: "Burkina Faso",
      burundi: "Burundi",
      cambodia: "Cambodia",
      cameroon: "Cameroon",
      canada: "Canada",
      central_african_republic: "Central African Republic",
      chad: "Chad",
      chile: "Chile",
      china: "China",
      colombia: "Colombia",
      comoros: "Comoros",
      congo: "Congo",
      costa_rica: "Costa Rica",
      croatia: "Croatia",
      cuba: "Cuba",
      curacao: "Curaçao",
      cyprus: "Cyprus",
      czechia: "Czechia",
      cote_divoire: "Côte d'Ivoire",
      denmark: "Denmark",
      djibouti: "Djibouti",
      dominica: "Dominica",
      dominican_republic: "Dominican Republic",
      ecuador: "Ecuador",
      egypt: "Egypt",
      el_salvador: "El Salvador",
      equatorial_guinea: "Equatorial Guinea",
      eritrea: "Eritrea",
      estonia: "Estonia",
      eswatini: "Eswatini",
      ethiopia: "Ethiopia",
      falkland_islands_malvinas: "Falkland Islands",
      fiji: "Fiji",
      finland: "Finland",
      france: "France",
      french_guiana: "French Guiana",
      gabon: "Gabon",
      gambia: "Gambia",
      georgia: "Georgia",
      germany: "Germany",
      ghana: "Ghana",
      gibraltar: "Gibraltar",
      greece: "Greece",
      greenland: "Greenland",
      grenada: "Grenada",
      guadeloupe: "Guadeloupe",
      guam: "Guam",
      guatemala: "Guatemala",
      guernsey: "Guernsey",
      guinea: "Guinea",
      guinea_bissau: "Guinea-Bissau",
      guyana: "Guyana",
      haiti: "Haiti",
      honduras: "Honduras",
      hong_kong: "Hong Kong",
      hungary: "Hungary",
      iceland: "Iceland",
      india: "India",
      indonesia: "Indonesia",
      iran: "Iran",
      iraq: "Iraq",
      ireland: "Ireland",
      israel: "Israel",
      italy: "Italy",
      jamaica: "Jamaica",
      japan: "Japan",
      jersey: "Jersey",
      jordan: "Jordan",
      kazakhstan: "Kazakhstan",
      kenya: "Kenya",
      kiribati: "Kiribati",
      kosovo: "Kosovo",
      kuwait: "Kuwait",
      kyrgyzstan: "Kyrgyzstan",
      laos: "Laos",
      latvia: "Latvia",
      lebanon: "Lebanon",
      lesotho: "Lesotho",
      liberia: "Liberia",
      libya: "Libya",
      liechtenstein: "Liechtenstein",
      lithuania: "Lithuania",
      luxembourg: "Luxembourg",
      macao: "Macao",
      madagascar: "Madagascar",
      malawi: "Malawi",
      malaysia: "Malaysia",
      maldives: "Maldives",
      mali: "Mali",
      malta: "Malta",
      martinique: "Martinique",
      mauritania: "Mauritania",
      mauritius: "Mauritius",
      mayotte: "Mayotte",
      mexico: "Mexico",
      micronesia: "Micronesia",
      moldova: "Moldova",
      monaco: "Monaco",
      mongolia: "Mongolia",
      montenegro: "Montenegro",
      montserrat: "Montserrat",
      morocco: "Morocco",
      mozambique: "Mozambique",
      myanmar: "Myanmar",
      namibia: "Namibia",
      nauru: "Nauru",
      nepal: "Nepal",
      netherlands: "Netherlands",
      new_caledonia: "New Caledonia",
      new_zealand: "New Zealand",
      nicaragua: "Nicaragua",
      niger: "Niger",
      nigeria: "Nigeria",
      niue: "Niue",
      north_korea: "North Korea",
      north_macedonia: "North Macedonia",
      norway: "Norway",
      oman: "Oman",
      pakistan: "Pakistan",
      palau: "Palau",
      palestine: "Palestine",
      panama: "Panama",
      papua_new_guinea: "Papua New Guinea",
      paraguay: "Paraguay",
      peru: "Peru",
      philippines: "Philippines",
      poland: "Poland",
      portugal: "Portugal",
      puerto_rico: "Puerto Rico",
      qatar: "Qatar",
      romania: "Romania",
      russia: "Russia",
      rwanda: "Rwanda",
      reunion: "Réunion",
      samoa: "Samoa",
      san_marino: "San Marino",
      saudi_arabia: "Saudi Arabia",
      senegal: "Senegal",
      serbia: "Serbia",
      seychelles: "Seychelles",
      sierra_leone: "Sierra Leone",
      singapore: "Singapore",
      slovakia: "Slovakia",
      slovenia: "Slovenia",
      somalia: "Somalia",
      south_africa: "South Africa",
      south_korea: "South Korea",
      south_sudan: "South Sudan",
      spain: "Spain",
      sri_lanka: "Sri Lanka",
      sudan: "Sudan",
      suriname: "Suriname",
      sweden: "Sweden",
      switzerland: "Switzerland",
      syria: "Syria",
      taiwan: "Taiwan",
      tajikistan: "Tajikistan",
      tanzania: "Tanzania",
      thailand: "Thailand",
      timor_leste: "Timor-Leste",
      togo: "Togo",
      tonga: "Tonga",
      trinidad_and_tobago: "Trinidad and Tobago",
      tunisia: "Tunisia",
      turkmenistan: "Turkmenistan",
      tuvalu: "Tuvalu",
      turkiye: "Türkiye",
      uganda: "Uganda",
      ukraine: "Ukraine",
      united_arab_emirates: "United Arab Emirates",
      united_kingdom: "United Kingdom",
      united_states: "United States",
      uruguay: "Uruguay",
      uzbekistan: "Uzbekistan",
      vanuatu: "Vanuatu",
      vatican_city_state: "Vatican City",
      venezuela: "Venezuela",
      vietnam: "Vietnam",
      western_sahara: "Western Sahara",
      yemen: "Yemen",
      zambia: "Zambia",
      zimbabwe: "Zimbabwe"
    }
  },
  games: {
    id: "games",
    title: "Video game characters",
    game_type: {
      lol: {
        id: "lol",
        game_name: "League of Legends",
        words: {
          ahri: "Ahri",
          bard: "Bard"
        }
      }
    }
  }
};