export default {
  objects: {
    id: "objects",
    title: "Objetos",
    words: {
      ball: "Pelota",
      pencil: "Lápiz",
      chair: "Silla",
      watch: "Reloj",
      balloon: "Globo",
      book: "Libro",
      box: "Caja",
      cup: "Taza",
      phone: "Teléfono",
      car: "Coche",
      bicycle: "Bicicleta",
      hammer: "Martillo",
      computer: "Computadora",
      lamp: "Lámpara",
      pants: "Pantalones",
      shirt: "Camisa",
      shoes: "Zapatos",
      glasses: "Gafas",
      hat: "Sombrero",
      perfume: "Perfume",
      camera: "Cámara",
      toothbrush: "Cepillo de dientes",
      mirror: "Espejo",
      lock: "Candado",
      key: "Llave",
      bag: "Bolso",
      suitcase: "Maleta",
      umbrella: "Paraguas",
      music_box: "Caja de música",
      wallet: "Billetera",
      piano: "Piano",
      guitar: "Guitarra",
      violin: "Violín",
      stuffed_animal: "Peluche",
      bed: "Cama",
      table: "Mesa",
      kitchen: "Cocina",
      fridge: "Nevera",
      hairbrush: "Cepillo de pelo",
      comb: "Peine",
      bottle: "Botella",
      newspaper: "Periódico",
      magazine: "Revista",
      tools: "Herramientas",
      broom: "Escoba",
      plant: "Planta",
      painting: "Pintura",
      ladder: "Escalera",
      paper: "Papel",
      canvas: "Lienzo",
      needle_and_thread: "Hilo y aguja",
      pen: "Bolígrafo",
      feather: "Pluma",
      eraser: "Borrador",
      tape: "Cinta adhesiva",
      ruler: "Regla",
      palette: "Paleta",
      radio: "Radio",
      speakers: "Altavoces",
      keyboard: "Teclado",
      mouse: "Ratón",
      calculator: "Calculadora",
      scissors: "Tijeras",
      pillow: "Almohada",
      blanket: "Manta",
      alarm_clock: "Reloj despertador",
      toy: "Juguete",
      crayons: "Crayones",
      markers: "Rotuladores",
      tape_measure: "Cinta métrica",
      sunglasses: "Gafas de sol",
      tie: "Corbata",
      keychain: "Llavero",
      calendar: "Calendario",
      stamp: "Sello",
      ashtray: "Cenicero",
      teapot: "Tetera",
      glass: "Vaso",
      plate: "Plato",
      spoon: "Cuchara",
      fork: "Tenedor",
      knife: "Cuchillo",
      can_opener: "Abrelatas",
      candleholder: "Candelabro",
      microphone: "Micrófono",
      toaster: "Tostadora",
      microwave: "Microondas",
      oven: "Cocina",
      refrigerator: "Refrigerador",
      shower: "Ducha",
      washing_machine: "Lavadora",
      coffee: "Café",
      coffee_maker: "Cafetera",
      tablet: "Tablet",
      television: "Televisor",
      printer: "Impresora",
      headphones: "Audífonos",
      door: "Puerta",
      window: "Ventana",
      fan: "Ventilador",
    }
  },
  countries: {
    id: "countries",
    title: "Países",
    words: {
      afghanistan: "Afganistán",
      albania: "Albania",
      algeria: "Argelia",
      andorra: "Andorra",
      angola: "Angola",
      anguilla: "Anguila",
      antarctica: "Antártida",
      antigua_and_barbuda: "Antigua y Barbuda",
      argentina: "Argentina",
      armenia: "Armenia",
      aruba: "Aruba",
      australia: "Australia",
      austria: "Austria",
      azerbaijan: "Azerbaiyán",
      bahamas: "Bahamas",
      bahrain: "Baréin",
      bangladesh: "Bangladés",
      barbados: "Barbados",
      belarus: "Bielorrusia",
      belgium: "Bélgica",
      belize: "Belice",
      benin: "Benín",
      bermuda: "Bermudas",
      bhutan: "Bután",
      bolivia: "Bolivia",
      bosnia_and_herzegovina: "Bosnia y Herzegovina",
      botswana: "Botsuana",
      brazil: "Brasil",
      brunei_darussalam: "Brunéi",
      bulgaria: "Bulgaria",
      burkina_faso: "Burkina Faso",
      burundi: "Burundi",
      cambodia: "Camboya",
      cameroon: "Camerún",
      canada: "Canadá",
      central_african_republic: "República Centroafricana",
      chad: "Chad",
      chile: "Chile",
      china: "China",
      colombia: "Colombia",
      comoros: "Comoras",
      congo: "Congo",
      costa_rica: "Costa Rica",
      croatia: "Croacia",
      cuba: "Cuba",
      curacao: "Curazao",
      cyprus: "Chipre",
      czechia: "Chequia",
      cote_divoire: "Costa de Marfil",
      denmark: "Dinamarca",
      djibouti: "Yibuti",
      dominica: "Dominica",
      dominican_republic: "República Dominicana",
      ecuador: "Ecuador",
      egypt: "Egipto",
      el_salvador: "El Salvador",
      equatorial_guinea: "Guinea Ecuatorial",
      eritrea: "Eritrea",
      estonia: "Estonia",
      eswatini: "Esuatini",
      ethiopia: "Etiopía",
      falkland_islands_malvinas: "Islas Malvinas",
      fiji: "Fiyi",
      finland: "Finlandia",
      france: "Francia",
      french_guiana: "Guayana Francesa",
      gabon: "Gabón",
      gambia: "Gambia",
      georgia: "Georgia",
      germany: "Alemania",
      ghana: "Ghana",
      gibraltar: "Gibraltar",
      greece: "Grecia",
      greenland: "Groenlandia",
      grenada: "Granada",
      guadeloupe: "Guadalupe",
      guam: "Guam",
      guatemala: "Guatemala",
      guernsey: "Guernsey",
      guinea: "Guinea",
      guinea_bissau: "Guinea-Bisáu",
      guyana: "Guyana",
      haiti: "Haití",
      honduras: "Honduras",
      hong_kong: "Hong Kong",
      hungary: "Hungría",
      iceland: "Islandia",
      india: "India",
      indonesia: "Indonesia",
      iran: "Irán",
      iraq: "Irak",
      ireland: "Irlanda",
      israel: "Israel",
      italy: "Italia",
      jamaica: "Jamaica",
      japan: "Japón",
      jersey: "Jersey",
      jordan: "Jordania",
      kazakhstan: "Kazajistán",
      kenya: "Kenia",
      kiribati: "Kiribati",
      kosovo: "Kosovo",
      kuwait: "Kuwait",
      kyrgyzstan: "Kirguistán",
      laos: "Laos",
      latvia: "Letonia",
      lebanon: "Líbano",
      lesotho: "Lesoto",
      liberia: "Liberia",
      libya: "Libia",
      liechtenstein: "Liechtenstein",
      lithuania: "Lituania",
      luxembourg: "Luxemburgo",
      macao: "Macao",
      madagascar: "Madagascar",
      malawi: "Malaui",
      malaysia: "Malasia",
      maldives: "Maldivas",
      mali: "Malí",
      malta: "Malta",
      martinique: "Martinica",
      mauritania: "Mauritania",
      mauritius: "Mauricio",
      mayotte: "Mayotte",
      mexico: "México",
      micronesia: "Micronesia",
      moldova: "Moldavia",
      monaco: "Mónaco",
      mongolia: "Mongolia",
      montenegro: "Montenegro",
      montserrat: "Montserrat",
      morocco: "Marruecos",
      mozambique: "Mozambique",
      myanmar: "Myanmar",
      namibia: "Namibia",
      nauru: "Nauru",
      nepal: "Nepal",
      netherlands: "Países Bajos",
      new_caledonia: "Nueva Caledonia",
      new_zealand: "Nueva Zelanda",
      nicaragua: "Nicaragua",
      niger: "Níger",
      nigeria: "Nigeria",
      niue: "Niue",
      north_korea: "Corea del Norte",
      north_macedonia: "Macedonia del Norte",
      norway: "Noruega",
      oman: "Omán",
      pakistan: "Pakistán",
      palau: "Palaos",
      palestine: "Palestina",
      panama: "Panamá",
      papua_new_guinea: "Papúa Nueva Guinea",
      paraguay: "Paraguay",
      peru: "Perú",
      philippines: "Filipinas",
      poland: "Polonia",
      portugal: "Portugal",
      puerto_rico: "Puerto Rico",
      qatar: "Catar",
      romania: "Rumania",
      russia: "Rusia",
      rwanda: "Ruanda",
      reunion: "Reunión",
      samoa: "Samoa",
      san_marino: "San Marino",
      saudi_arabia: "Arabia Saudita",
      senegal: "Senegal",
      serbia: "Serbia",
      seychelles: "Seychelles",
      sierra_leone: "Sierra Leona",
      singapore: "Singapur",
      slovakia: "Eslovaquia",
      slovenia: "Eslovenia",
      somalia: "Somalia",
      south_africa: "Sudáfrica",
      south_korea: "Corea del Sur",
      south_sudan: "Sudán del Sur",
      spain: "España",
      sri_lanka: "Sri Lanka",
      sudan: "Sudán",
      suriname: "Surinam",
      sweden: "Suecia",
      switzerland: "Suiza",
      syria: "Siria",
      taiwan: "Taiwán",
      tajikistan: "Tayikistán",
      tanzania: "Tanzania",
      thailand: "Tailandia",
      timor_leste: "Timor Oriental",
      togo: "Togo",
      tonga: "Tonga",
      trinidad_and_tobago: "Trinidad y Tobago",
      tunisia: "Túnez",
      turkmenistan: "Turkmenistán",
      tuvalu: "Tuvalu",
      turkiye: "Turquía",
      uganda: "Uganda",
      ukraine: "Ucrania",
      united_arab_emirates: "Emiratos Árabes Unidos",
      united_kingdom: "Reino Unido",
      united_states: "Estados Unidos",
      uruguay: "Uruguay",
      uzbekistan: "Uzbekistán",
      vanuatu: "Vanuatu",
      vatican_city_state: "Ciudad del Vaticano",
      venezuela: "Venezuela",
      vietnam: "Vietnam",
      western_sahara: "Sahara Occidental",
      yemen: "Yemen",
      zambia: "Zambia",
      zimbabwe: "Zimbabue"
    }
  },
  games: {
    id: "games",
    title: "Videojuegos",
    game_type: {
      lol: {
        id: "lol",
        game_name: "League of Legends",
        words: {
          aatrox: "Aatrox",
          ahri: "Ahri",
          akali: "Akali",
          akshan: "Akshan",
          alistar: "Alistar",
          amumu: "Amumu",
          anivia: "Anivia",
          annie: "Annie",
          aphelios: "Aphelios",
          ashe: "Ashe",
          aurelion_sol: "Aurelion Sol",
          azir: "Azir",
          bard: "Bardo",
          bel_veth: "Bel'veth",
          blitzcrank: "Blitzcrank",
          brand: "Brand",
          braum: "Braum",
          caitlyn: "Caitlyn",
          camille: "Camille",
          cassiopeia: "Cassiopeia",
          cho_gath: "Cho'Gath",
          corki: "Corki",
          darius: "Darius",
          diana: "Diana",
          dr_mundo: "Dr Mundo",
          draven: "Draven",
          ekko: "Ekko",
          evelynn: "Evelynn",
          ezreal: "Ezreal",
          fiddlesticks: "Fiddlesticks",
          fiora: "Fiora",
          gangplank: "Gangplank",
          garen: "Garen",
          gnar: "Gnar",
          gragas: "Gragas",
          graves: "Graves",
          gwen: "Gwen",
          hecarim: "Hecarim",
          heimerdinger: "Heimerdinger",
          illaoi: "Illaoi",
          irelia: "Irelia",
          ivern: "Ivern",
          janna: "Janna",
          jarvan_iv: "Jarvan IV",
          jax: "Jax",
          jayce: "Jayce",
          jhin: "Jhin",
          jinx: "Jinx",
          k_sante: "K'Sante",
          kai_sa: "Kai'Sa",
          kalista: "Kalista",
          karma: "Karma",
          karthus: "Karthus",
          kassadin: "Kassadin",
          katarina: "Katarina",
          kayle: "Kayle",
          kayn: "Kayn",
          kennen: "Kennen",
          kha_zix: "Kha'Zix",
          kindred: "Kindred",
          kled: "Kled",
          kog_maw: "Kog'Maw",
          leblanc: "LeBlanc",
          lee_sin: "Lee Sin",
          leona: "Leona",
          lillia: "Lillia",
          lissandra: "Lissandra",
          lucian: "Lucian",
          lulu: "Lulu",
          lux: "Lux",
          malphite: "Malphite",
          malzahar: "Malzahar",
          maokai: "Maokai",
          master_yi: "Maestro Yi",
          milio: "Milio",
          miss_fortune: "Miss Fortune",
          mordekaiser: "Mordekaiser",
          morgana: "Morgana",
          naafiri: "Naafiri",
          nami: "Nami",
          nasus: "Nasus",
          nautilus: "Nautilus",
          neeko: "Neeko",
          nidalee: "Nidalee",
          nilah: "Nilah",
          nocturne: "Nocturne",
          nunu: "Nunu",
          olaf: "Olaf",
          orianna: "Orianna",
          ornn: "Ornn",
          pantheon: "Pantheon",
          poppy: "Poppy",
          pyke: "Pyke",
          qiyana: "Qiyana",
          quinn: "Quinn",
          rakan: "Rakan",
          rammus: "Rammus",
          rek_sai: "Rek'Sai",
          rell: "Rell",
          renata_glasc: "Renata Glasc",
          renekton: "Renekton",
          rengar: "Rengar",
          riven: "Riven",
          rumble: "Rumble",
          ryze: "Ryze",
          samira: "Samira",
          sejuani: "Sejuani",
          senna: "Senna",
          seraphine: "Seraphine",
          sett: "Sett",
          shaco: "Shaco",
          shen: "Shen",
          shyvana: "Shyvana",
          singed: "Singed",
          sion: "Sion",
          sivir: "Sivir",
          skarner: "Skarner",
          sona: "Sona",
          soraka: "Soraka",
          swain: "Swain",
          sylas: "Sylas",
          syndra: "Syndra",
          tahm_kench: "Tahm Kench",
          taliyah: "Taliyah",
          talon: "Talon",
          taric: "Taric",
          teemo: "Teemo",
          thresh: "Thresh",
          tristana: "Tristana",
          trundle: "Trundle",
          tryndamere: "Tryndamere",
          twitch: "Twitch",
          udyr: "Udyr",
          urgot: "Urgot",
          varus: "Varus",
          vayne: "Vayne",
          veigar: "Veigar",
          velkoz: "Vel'Koz",
          vex: "Vex",
          vi: "Vi",
          viego: "Viego",
          viktor: "Viktor",
          vladimir: "Vladimir",
          volibear: "Volibear",
          warwick: "Warwick",
          wukong: "Wukong",
          xayah: "Xayah",
          xerath: "Xerath",
          xin_zhao: "Xin Zhao",
          yasuo: "Yasuo",
          yone: "Yone",
          yorick: "Yorick",
          yuumi: "Yuumi",
          zac: "Zac",
          zed: "Zed",
          zeri: "Zeri",
          ziggs: "Ziggs",
          zilean: "Zilean",
          zoe: "Zoe",
          zyra: "Zyra"
        }
      },
      valorant: {
        id: "valorant",
        game_name: "Valorant",
        words: {
          astra: "Astra",
          breach: "Breach",
          brimstone: "Brimstone",
          chamber: "Chamber",
          cypher: "Cypher",
          deadlock: "Deadlock",
          fade: "Fade",
          gekko: "Gekko",
          harbor: "Harbor",
          jett: "Jett",
          kayo: "Kayo",
          killjoy: "Killjoy",
          neon: "Neon",
          omen: "Omen",
          phoenix: "Phoenix",
          raze: "Raze",
          reyna: "Reyna",
          sage: "Sage",
          skye: "Skye",
          sova: "Sova",
          viper: "Viper",
          yoru: "Yoru",
          classic: "Classic",
          ghost: "Ghost",
          shorty: "Shorty",
          frenzy: "Frenzy",
          sheriff: "Sheriff",
          stinger: "Stinger",
          spectre: "Spectre",
          bucky: "Bucky",
          judge: "Judge",
          bulldog: "Bulldog",
          guardian: "Guardian",
          phantom: "Phantom",
          vandal: "Vandal",
          marshal: "Marshal",
          operator: "Operator",
          ares: "Ares",
          odin: "Odin",
          knife: "Cuchillo",
        }
      }
    }
  }
};