export default {
  objects: {
    id: "objects",
    title: "Objetos",
    words: {
      ball: "Pelota",
      pencil: "Lápiz",
      chair: "Silla",
      watch: "Reloj",
      balloon: "Globo",
      book: "Libro",
      box: "Caja",
      cup: "Taza",
      phone: "Teléfono",
      car: "Coche",
      bicycle: "Bicicleta",
      hammer: "Martillo",
      computer: "Computadora",
      lamp: "Lámpara",
      brush: "Cepillo",
      pants: "Pantalones",
      shirt: "Camisa",
      shoes: "Zapatos",
      glasses: "Gafas",
      hat: "Sombrero",
      perfume: "Perfume",
      camera: "Cámara",
      toothbrush: "Cepillo de dientes",
      mirror: "Espejo",
      lock: "Candado",
      key: "Llave",
      bag: "Bolso",
      suitcase: "Maleta",
      umbrella: "Paraguas",
      music_box: "Caja de música",
      wallet: "Cartera",
      purse: "Billetera",
      piano: "Piano",
      guitar: "Guitarra",
      violin: "Violín",
      stuffed_animal: "Peluche",
      bed: "Cama",
      table: "Mesa",
      kitchen: "Cocina",
      fridge: "Nevera",
      hairbrush: "Cepillo de pelo",
      comb: "Peine",
      bottle: "Botella",
      newspaper: "Periódico",
      magazine: "Revista",
      tools: "Herramientas",
      broom: "Escoba",
      plant: "Planta",
      painting: "Pintura",
      ladder: "Escalera",
      paper: "Papel",
      canvas: "Lienzo",
      needle_and_thread: "Hilo y aguja",
      pen: "Bolígrafo",
      feather: "Pluma",
      eraser: "Goma de borrar",
      tape: "Cinta adhesiva",
      ruler: "Regla",
      palette: "Paleta",
      typewriter: "Máquina de escribir",
      radio: "Radio",
      speakers: "Altavoces",
      keyboard: "Teclado",
      mouse: "Ratón",
      calculator: "Calculadora",
      scissors: "Tijeras",
      pillow: "Almohada",
      blanket: "Manta",
      alarm_clock: "Reloj despertador",
      toy: "Juguete",
      crayons: "Crayones",
      markers: "Rotuladores",
      tape_measure: "Cinta métrica",
      sunglasses: "Gafas de sol",
      tie: "Corbata",
      keychain: "Llavero",
      calendar: "Calendario",
      stamp: "Sello",
      ashtray: "Cenicero",
      electric_kettle: "Hervidor eléctrico",
      glass: "Vaso",
      plate: "Plato",
      spoon: "Cuchara",
      fork: "Tenedor",
      knife: "Cuchillo",
      teaspoon: "Cucharita",
      can_opener: "Abrelatas",
      candleholder: "Candelabro"
    }
  },
  countries: {
    id: "countries",
    title: "Países",
    words: {
      panama: "Panamá"
    }
  },
  games: {
    id: "games",
    title: "Personajes de videojuegos",
    game_type: {
      lol: {
        id: "lol",
        game_name: "League of Legends",
        words: {
          ahri: "Ahri",
          bard: "Bardo"
        }
      }
    }
  }
};