export default {
  objects: {
    id: "objects",
    title: "Objects",
    words: {
      ball: "Ball",
      pencil: "Pencil",
      chair: "Chair",
      watch: "Watch",
      balloon: "Balloon",
      book: "Book",
      box: "Box",
      cup: "Cup",
      phone: "Phone",
      car: "Car",
      bicycle: "Bicycle",
      hammer: "Hammer",
      computer: "Computer",
      lamp: "Lamp",
      brush: "Brush",
      pants: "Pants",
      shirt: "Shirt",
      shoes: "Shoes",
      glasses: "Glasses",
      hat: "Hat",
      perfume: "Perfume",
      camera: "Camera",
      toothbrush: "Toothbrush",
      mirror: "Mirror",
      lock: "Lock",
      key: "Key",
      bag: "Bag",
      suitcase: "Suitcase",
      umbrella: "Umbrella",
      music_box: "Music Box",
      wallet: "Wallet",
      purse: "Purse",
      piano: "Piano",
      guitar: "Guitar",
      violin: "Violin",
      stuffed_animal: "Stuffed Animal",
      bed: "Bed",
      table: "Table",
      kitchen: "Kitchen",
      fridge: "Fridge",
      hairbrush: "Hairbrush",
      comb: "Comb",
      bottle: "Bottle",
      newspaper: "Newspaper",
      magazine: "Magazine",
      tools: "Tools",
      broom: "Broom",
      plant: "Plant",
      painting: "Painting",
      ladder: "Ladder",
      paper: "Paper",
      canvas: "Canvas",
      needle_and_thread: "Needle and Thread",
      pen: "Pen",
      feather: "Feather",
      eraser: "Eraser",
      tape: "Tape",
      ruler: "Ruler",
      palette: "Palette",
      typewriter: "Typewriter",
      radio: "Radio",
      speakers: "Speakers",
      keyboard: "Keyboard",
      mouse: "Mouse",
      calculator: "Calculator",
      scissors: "Scissors",
      pillow: "Pillow",
      blanket: "Blanket",
      alarm_clock: "Alarm Clock",
      toy: "Toy",
      crayons: "Crayons",
      markers: "Markers",
      tape_measure: "Tape Measure",
      sunglasses: "Sunglasses",
      tie: "Tie",
      keychain: "Keychain",
      calendar: "Calendar",
      stamp: "Stamp",
      ashtray: "Ashtray",
      electric_kettle: "Electric Kettle",
      glass: "Glass",
      plate: "Plate",
      spoon: "Spoon",
      fork: "Fork",
      knife: "Knife",
      teaspoon: "Teaspoon",
      can_opener: "Can Opener",
      candleholder: "Candleholder"
    }
  },
  countries: {
    id: "countries",
    title: "Countries",
    words: {
      panama: "Panama"
    }
  },
  games: {
    id: "games",
    title: "Video game characters",
    game_type: {
      lol: {
        id: "lol",
        game_name: "League of Legends",
        words: {
          ahri: "Ahri",
          bard: "Bard"
        }
      }
    }
  }
};