export default {
  objects: {
    id: "objects",
    title: "Objetos",
    words: {
      ball: "Pelota",
      pencil: "Lápiz",
      chair: "Silla",
      watch: "Reloj",
      balloon: "Globo",
      book: "Libro",
      box: "Caja",
      cup: "Taza",
      phone: "Teléfono",
      car: "Coche",
      bicycle: "Bicicleta",
      hammer: "Martillo",
      computer: "Computadora",
      lamp: "Lámpara",
      brush: "Cepillo",
      pants: "Pantalones",
      shirt: "Camisa",
      shoes: "Zapatos",
      glasses: "Gafas",
      hat: "Sombrero",
      perfume: "Perfume",
      camera: "Cámara",
      toothbrush: "Cepillo de dientes",
      mirror: "Espejo",
      lock: "Candado",
      key: "Llave",
      bag: "Bolso",
      suitcase: "Maleta",
      umbrella: "Paraguas",
      music_box: "Caja de música",
      wallet: "Cartera",
      purse: "Billetera",
      piano: "Piano",
      guitar: "Guitarra",
      violin: "Violín",
      stuffed_animal: "Peluche",
      bed: "Cama",
      table: "Mesa",
      kitchen: "Cocina",
      fridge: "Nevera",
      hairbrush: "Cepillo de pelo",
      comb: "Peine",
      bottle: "Botella",
      newspaper: "Periódico",
      magazine: "Revista",
      tools: "Herramientas",
      broom: "Escoba",
      plant: "Planta",
      painting: "Pintura",
      ladder: "Escalera",
      paper: "Papel",
      canvas: "Lienzo",
      needle_and_thread: "Hilo y aguja",
      pen: "Bolígrafo",
      feather: "Pluma",
      eraser: "Goma de borrar",
      tape: "Cinta adhesiva",
      ruler: "Regla",
      palette: "Paleta",
      typewriter: "Máquina de escribir",
      radio: "Radio",
      speakers: "Altavoces",
      keyboard: "Teclado",
      mouse: "Ratón",
      calculator: "Calculadora",
      scissors: "Tijeras",
      pillow: "Almohada",
      blanket: "Manta",
      alarm_clock: "Reloj despertador",
      toy: "Juguete",
      crayons: "Crayones",
      markers: "Rotuladores",
      tape_measure: "Cinta métrica",
      sunglasses: "Gafas de sol",
      tie: "Corbata",
      keychain: "Llavero",
      calendar: "Calendario",
      stamp: "Sello",
      ashtray: "Cenicero",
      electric_kettle: "Hervidor eléctrico",
      glass: "Vaso",
      plate: "Plato",
      spoon: "Cuchara",
      fork: "Tenedor",
      knife: "Cuchillo",
      teaspoon: "Cucharita",
      can_opener: "Abrelatas",
      candleholder: "Candelabro"
    }
  },
  countries: {
    id: "countries",
    title: "Países",
    words: {
      afghanistan: "Afganistán",
      albania: "Albania",
      algeria: "Argelia",
      andorra: "Andorra",
      angola: "Angola",
      anguilla: "Anguila",
      antarctica: "Antártida",
      antigua_and_barbuda: "Antigua y Barbuda",
      argentina: "Argentina",
      armenia: "Armenia",
      aruba: "Aruba",
      australia: "Australia",
      austria: "Austria",
      azerbaijan: "Azerbaiyán",
      bahamas: "Bahamas",
      bahrain: "Baréin",
      bangladesh: "Bangladés",
      barbados: "Barbados",
      belarus: "Bielorrusia",
      belgium: "Bélgica",
      belize: "Belice",
      benin: "Benín",
      bermuda: "Bermudas",
      bhutan: "Bután",
      bolivia: "Bolivia",
      bosnia_and_herzegovina: "Bosnia y Herzegovina",
      botswana: "Botsuana",
      brazil: "Brasil",
      brunei_darussalam: "Brunéi",
      bulgaria: "Bulgaria",
      burkina_faso: "Burkina Faso",
      burundi: "Burundi",
      cambodia: "Camboya",
      cameroon: "Camerún",
      canada: "Canadá",
      central_african_republic: "República Centroafricana",
      chad: "Chad",
      chile: "Chile",
      china: "China",
      colombia: "Colombia",
      comoros: "Comoras",
      congo: "Congo",
      costa_rica: "Costa Rica",
      croatia: "Croacia",
      cuba: "Cuba",
      curacao: "Curazao",
      cyprus: "Chipre",
      czechia: "Chequia",
      cote_divoire: "Costa de Marfil",
      denmark: "Dinamarca",
      djibouti: "Yibuti",
      dominica: "Dominica",
      dominican_republic: "República Dominicana",
      ecuador: "Ecuador",
      egypt: "Egipto",
      el_salvador: "El Salvador",
      equatorial_guinea: "Guinea Ecuatorial",
      eritrea: "Eritrea",
      estonia: "Estonia",
      eswatini: "Esuatini",
      ethiopia: "Etiopía",
      falkland_islands_malvinas: "Islas Malvinas",
      fiji: "Fiyi",
      finland: "Finlandia",
      france: "Francia",
      french_guiana: "Guayana Francesa",
      gabon: "Gabón",
      gambia: "Gambia",
      georgia: "Georgia",
      germany: "Alemania",
      ghana: "Ghana",
      gibraltar: "Gibraltar",
      greece: "Grecia",
      greenland: "Groenlandia",
      grenada: "Granada",
      guadeloupe: "Guadalupe",
      guam: "Guam",
      guatemala: "Guatemala",
      guernsey: "Guernsey",
      guinea: "Guinea",
      guinea_bissau: "Guinea-Bisáu",
      guyana: "Guyana",
      haiti: "Haití",
      honduras: "Honduras",
      hong_kong: "Hong Kong",
      hungary: "Hungría",
      iceland: "Islandia",
      india: "India",
      indonesia: "Indonesia",
      iran: "Irán",
      iraq: "Irak",
      ireland: "Irlanda",
      israel: "Israel",
      italy: "Italia",
      jamaica: "Jamaica",
      japan: "Japón",
      jersey: "Jersey",
      jordan: "Jordania",
      kazakhstan: "Kazajistán",
      kenya: "Kenia",
      kiribati: "Kiribati",
      kosovo: "Kosovo",
      kuwait: "Kuwait",
      kyrgyzstan: "Kirguistán",
      laos: "Laos",
      latvia: "Letonia",
      lebanon: "Líbano",
      lesotho: "Lesoto",
      liberia: "Liberia",
      libya: "Libia",
      liechtenstein: "Liechtenstein",
      lithuania: "Lituania",
      luxembourg: "Luxemburgo",
      macao: "Macao",
      madagascar: "Madagascar",
      malawi: "Malaui",
      malaysia: "Malasia",
      maldives: "Maldivas",
      mali: "Malí",
      malta: "Malta",
      martinique: "Martinica",
      mauritania: "Mauritania",
      mauritius: "Mauricio",
      mayotte: "Mayotte",
      mexico: "México",
      micronesia: "Micronesia",
      moldova: "Moldavia",
      monaco: "Mónaco",
      mongolia: "Mongolia",
      montenegro: "Montenegro",
      montserrat: "Montserrat",
      morocco: "Marruecos",
      mozambique: "Mozambique",
      myanmar: "Myanmar",
      namibia: "Namibia",
      nauru: "Nauru",
      nepal: "Nepal",
      netherlands: "Países Bajos",
      new_caledonia: "Nueva Caledonia",
      new_zealand: "Nueva Zelanda",
      nicaragua: "Nicaragua",
      niger: "Níger",
      nigeria: "Nigeria",
      niue: "Niue",
      north_korea: "Corea del Norte",
      north_macedonia: "Macedonia del Norte",
      norway: "Noruega",
      oman: "Omán",
      pakistan: "Pakistán",
      palau: "Palaos",
      palestine: "Palestina",
      panama: "Panamá",
      papua_new_guinea: "Papúa Nueva Guinea",
      paraguay: "Paraguay",
      peru: "Perú",
      philippines: "Filipinas",
      poland: "Polonia",
      portugal: "Portugal",
      puerto_rico: "Puerto Rico",
      qatar: "Catar",
      romania: "Rumania",
      russia: "Rusia",
      rwanda: "Ruanda",
      reunion: "Reunión",
      samoa: "Samoa",
      san_marino: "San Marino",
      saudi_arabia: "Arabia Saudita",
      senegal: "Senegal",
      serbia: "Serbia",
      seychelles: "Seychelles",
      sierra_leone: "Sierra Leona",
      singapore: "Singapur",
      slovakia: "Eslovaquia",
      slovenia: "Eslovenia",
      somalia: "Somalia",
      south_africa: "Sudáfrica",
      south_korea: "Corea del Sur",
      south_sudan: "Sudán del Sur",
      spain: "España",
      sri_lanka: "Sri Lanka",
      sudan: "Sudán",
      suriname: "Surinam",
      sweden: "Suecia",
      switzerland: "Suiza",
      syria: "Siria",
      taiwan: "Taiwán",
      tajikistan: "Tayikistán",
      tanzania: "Tanzania",
      thailand: "Tailandia",
      timor_leste: "Timor Oriental",
      togo: "Togo",
      tonga: "Tonga",
      trinidad_and_tobago: "Trinidad y Tobago",
      tunisia: "Túnez",
      turkmenistan: "Turkmenistán",
      tuvalu: "Tuvalu",
      turkiye: "Turquía",
      uganda: "Uganda",
      ukraine: "Ucrania",
      united_arab_emirates: "Emiratos Árabes Unidos",
      united_kingdom: "Reino Unido",
      united_states: "Estados Unidos",
      uruguay: "Uruguay",
      uzbekistan: "Uzbekistán",
      vanuatu: "Vanuatu",
      vatican_city_state: "Ciudad del Vaticano",
      venezuela: "Venezuela",
      vietnam: "Vietnam",
      western_sahara: "Sahara Occidental",
      yemen: "Yemen",
      zambia: "Zambia",
      zimbabwe: "Zimbabue"
    }
  },
  games: {
    id: "games",
    title: "Personajes de videojuegos",
    game_type: {
      lol: {
        id: "lol",
        game_name: "League of Legends",
        words: {
          ahri: "Ahri",
          bard: "Bardo"
        }
      }
    }
  }
};